In [2]:
from sklearn.datasets import load_iris
iris = load_iris()

In [3]:
X = iris.data
y = iris.target

In [9]:
print(X.shape)
print(y.shape)
iris.feature_names

(150, 4)
(150,)


['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [7]:
import pandas as pd

In [10]:
irisDf = pd.DataFrame(X, columns = iris.feature_names)

In [12]:
irisDf.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

[5 rows x 4 columns]

In [13]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [19]:
from sklearn.neighbors import KNeighborsClassifier

In [20]:
knn = KNeighborsClassifier()
knn.fit(X, y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           n_neighbors=5, p=2, weights='uniform')

In [23]:
knn.predict([3,5,4,2])

array([1])

In [33]:
simple_train = ['Call you tonight', 'Call me a cab', 'please call me... PLEASE!']

In [25]:
from sklearn.feature_extraction.text import CountVectorizer

In [34]:
vect = CountVectorizer()

In [35]:
vect.fit(simple_train)

CountVectorizer(analyzer=u'word', binary=False, charset=None,
        charset_error=None, decode_error=u'strict',
        dtype=<type 'numpy.int64'>, encoding=u'utf-8', input=u'content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern=u'(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [36]:
vect.get_feature_names()

[u'cab', u'call', u'me', u'please', u'tonight', u'you']

In [37]:
simple_train_dtm = vect.transform(simple_train)

In [38]:
simple_train_dtm

<3x6 sparse matrix of type '<type 'numpy.int64'>'
	with 9 stored elements in Compressed Sparse Row format>

In [40]:
simple_train_dtm.toarray()

array([[0, 1, 0, 0, 1, 1],
       [1, 1, 1, 0, 0, 0],
       [0, 1, 1, 2, 0, 0]])

In [41]:
pd.DataFrame(simple_train_dtm.toarray(), columns = vect.get_feature_names())

cab  call  me  please  tonight  you
0    0     1   0       0        1    1
1    1     1   1       0        0    0
2    0     1   1       2        0    0

[3 rows x 6 columns]

In [42]:
type(simple_train_dtm)

scipy.sparse.csr.csr_matrix

In [43]:
print(simple_train_dtm)

  (0, 1)	1
  (0, 4)	1
  (0, 5)	1
  (1, 0)	1
  (1, 1)	1
  (1, 2)	1
  (2, 1)	1
  (2, 2)	1
  (2, 3)	2


In [44]:
simple_test = ["please don't call me"]

In [45]:
simple_test_dtm = vect.transform(simple_test)

In [46]:
simple_test_dtm.toarray()

array([[0, 1, 1, 1, 0, 0]])

In [48]:
pd.DataFrame(simple_test_dtm.toarray(), columns = vect.get_feature_names()).head()

cab  call  me  please  tonight  you
0    0     1   1       1        0    0

[1 rows x 6 columns]